sudo: false  # Use container-based infrastructure
language: python
python:
  - "2.7"
  - "3.4"
install:
  - pip install .
  - pip install coveralls
  - pip install pypandoc
script:
  - nosetests test --with-coverage --cover-package=topeology && ./lint.sh
after_success:
  coveralls